# Generated by Django 5.1.6 on 2025-02-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
    ]
