# Generated by Django 5.1.6 on 2025-03-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='offer_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
