# Generated by Django 5.1.6 on 2025-03-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_category_categoryoffer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='upated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
