# Generated by Django 5.1.6 on 2025-03-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_wallettransaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
