# Generated by Django 5.1.6 on 2025-04-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_wallettransaction_transaction_id_alter_wallet_user'),
        ('orders', '0043_rename_discount_amount_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order'),
        ),
    ]
