# Generated by Django 5.1.6 on 2025-02-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='pin_code',
            field=models.CharField(max_length=10),
        ),
    ]
