# Generated by Django 5.1.6 on 2025-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_varaint',
            new_name='product_variant',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payment')], default='COD', max_length=50),
        ),
    ]
