# Generated by Django 5.1.6 on 2025-02-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_product_varaint_order_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('deliverd', 'deliverd'), ('cancelled', 'cancelled')], default='pending', max_length=30),
        ),
    ]
