# Generated by Django 5.1.6 on 2025-03-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
