# Generated by Django 5.1.6 on 2025-03-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='68FABCDD', max_length=30, unique=True),
        ),
    ]
