# Generated by Django 5.1.6 on 2025-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_coupon_usage_limit_alter_coupon_code_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='44C3AE60', max_length=30, unique=True),
        ),
    ]
