# Generated by Django 5.1.6 on 2025-03-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='4F135077', max_length=30, unique=True),
        ),
    ]
