# Generated by Django 5.1.6 on 2025-03-21 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_coupon_code_orderreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='C98D4783', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem'),
        ),
    ]
