# Generated by Django 5.1.6 on 2025-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_coupon_code_alter_orderreturn_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='7AE133B6', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='return_status',
            field=models.CharField(choices=[('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_completed', 'Return Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
