# Generated by Django 5.1.6 on 2025-03-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_coupon_code_alter_orderreturn_return_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='39B6ED99', max_length=30, unique=True),
        ),
    ]
