# Generated by Django 5.1.6 on 2025-03-26 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_order_total_price_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreturn',
            name='return_status',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='D8C51EA1', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
