# Generated by Django 5.1.6 on 2025-03-27 05:46

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_coupon_code_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreturn',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='update_at',
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='return_type',
            field=models.CharField(choices=[('order', 'Full Order Return'), ('item', 'Single Item Return')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected'), ('completed', 'Return Completed')], default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=orders.models.generate_coupon_code, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='reason',
            field=models.CharField(choices=[('wrong_item', 'Wrong Item Received'), ('defective', 'Defective Product'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=20),
        ),
    ]
