# Generated by Django 5.1.6 on 2025-03-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_orderreturn_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreturn',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='return_type',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='D6DFE885', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='reason',
            field=models.TextField(),
        ),
    ]
