# Generated by Django 5.1.6 on 2025-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_remove_order_status_order_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='52112896', max_length=30, unique=True),
        ),
    ]
