# Generated by Django 5.1.6 on 2025-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_order_coupon_discount_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='2C0BFA74', max_length=30, unique=True),
        ),
    ]
