# Generated by Django 5.1.6 on 2025-04-01 07:17

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=orders.models.generate_coupon_code, max_length=30, unique=True),
        ),
    ]
