# Generated by Django 5.1.6 on 2025-03-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='Brand',
        ),
    ]
