# Generated by Django 5.1.6 on 2025-03-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_porductoffer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorductOffer',
            new_name='ProductOffer',
        ),
    ]
