# Generated by Django 5.1.6 on 2025-03-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_porductoffer_productoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='discound_percentage',
            new_name='discount_percentage',
        ),
    ]
