# Generated by Django 5.1.6 on 2025-03-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_discound_percentage_productoffer_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='offer_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
