# Generated by Django 5.1.6 on 2025-03-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productoffer_offer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
